name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install poetry

      - name: Poetry Install
        run: poetry install

      #- run: poetry run pylama # Disabled for now as black and pylama have different line length abilities with docstrings

      - name: Black Lint
        run: poetry run black --check --preview .

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
